#!/bin/bash
set -o errexit -o nounset -o pipefail -o xtrace

default() {
    make PREFIX=$PREFIX install
}

cd $SRCDIR
if [ -x ../../scripts/install ]; then
    source ../../scripts/install
else
    default
fi
